## EDA And Feature Engineering Of Google Play Store Dataset

1) Problem statement.
Today, 1.85 million different apps are available for users to download. Android users have even more from which to choose, with 2.56 million available through the Google Play Store. These apps have come to play a huge role in the way we live our lives today. Our Objective is to find the Most Popular Category, find the App with largest number of installs , the App with largest size etc.
2) Data Collection.

The data consists of 20 column and 10841 rows.

### Steps We Are Going to Follow
1. Data Clearning
2. Exploratory Data Analysis
3. Featur eEngineering

In [1]:
print("hello")

hello

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [5]:
df=pd.read_csv('https://raw.githubusercontent.com/krishnaik06/playstore-Dataset/main/googleplaystore.csv')
df.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up

In [6]:
df.shape

(10841, 13)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [9]:
# Summary of the dataset
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [11]:
# Missing Value
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

### Insights and observations

The datasest has the missing values

In [12]:
df.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up

## Data Cleaning:-

In [ ]:
df['Reviews'].unique()

<StringArray>
[   '159',    '967',  '87510', '215644',    '167',    '178',  '36815',
  '13791',    '121',  '13880',
 ...
   '2036',  '56496', '376223',    '785',   '5775',    '885',  '88486',
    '603',   '1195', '398307']
Length: 6002, dtype: str

In [17]:
df['Reviews'].str.isnumeric().sum()

np.int64(10840)

In [ ]:
# check if all the value is numeric or not

df[~df['Reviews'].str.isnumeric()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [20]:
df_copy=df.copy()

In [22]:
df_copy = df_copy.drop(df_copy.index[10472])

In [24]:
df_copy[~df_copy['Reviews'].str.isnumeric()]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [26]:
# convert reviws datatype to int 
df_copy['Reviews']=df_copy['Reviews'].astype(int)

In [27]:
df_copy.info()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            10840 non-null  str
 5   Installs        10840 non-null  str
 6   Type            10839 non-null  str
 7   Price           10840 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), int64(1), str(11)
memory usage: 1.2 MB

In [34]:
df_copy['Size'].unique().tolist()

['19M',
 '14M',
 '8.7M',
 '25M',
 '2.8M',
 '5.6M',
 '29M',
 '33M',
 '3.1M',
 '28M',
 '12M',
 '20M',
 '21M',
 '37M',
 '2.7M',
 '5.5M',
 '17M',
 '39M',
 '31M',
 '4.2M',
 '7.0M',
 '23M',
 '6.0M',
 '6.1M',
 '4.6M',
 '9.2M',
 '5.2M',
 '11M',
 '24M',
 'Varies with device',
 '9.4M',
 '15M',
 '10M',
 '1.2M',
 '26M',
 '8.0M',
 '7.9M',
 '56M',
 '57M',
 '35M',
 '54M',
 '201k',
 '3.6M',
 '5.7M',
 '8.6M',
 '2.4M',
 '27M',
 '2.5M',
 '16M',
 '3.4M',
 '8.9M',
 '3.9M',
 '2.9M',
 '38M',
 '32M',
 '5.4M',
 '18M',
 '1.1M',
 '2.2M',
 '4.5M',
 '9.8M',
 '52M',
 '9.0M',
 '6.7M',
 '30M',
 '2.6M',
 '7.1M',
 '3.7M',
 '22M',
 '7.4M',
 '6.4M',
 '3.2M',
 '8.2M',
 '9.9M',
 '4.9M',
 '9.5M',
 '5.0M',
 '5.9M',
 '13M',
 '73M',
 '6.8M',
 '3.5M',
 '4.0M',
 '2.3M',
 '7.2M',
 '2.1M',
 '42M',
 '7.3M',
 '9.1M',
 '55M',
 '23k',
 '6.5M',
 '1.5M',
 '7.5M',
 '51M',
 '41M',
 '48M',
 '8.5M',
 '46M',
 '8.3M',
 '4.3M',
 '4.7M',
 '3.3M',
 '40M',
 '7.8M',
 '8.8M',
 '6.6M',
 '5.1M',
 '61M',
 '66M',
 '79k',
 '8.4M',
 '118k',
 '44M',
 '695k',
 '1.6M',
 '6.2M',
 '18k',
 '53M',
 '1.4M',
 '3.0M',
 '5.8M',
 '3.8M',
 '9.6M',
 '45M',
 '63M',
 '49M',
 '77M',
 '4.4M',
 '4.8M',
 '70M',
 '6.9M',
 '9.3M',
 '10.0M',
 '8.1M',
 '36M',
 '84M',
 '97M',
 '2.0M',
 '1.9M',
 '1.8M',
 '5.3M',
 '47M',
 '556k',
 '526k',
 '76M',
 '7.6M',
 '59M',
 '9.7M',
 '78M',
 '72M',
 '43M',
 '7.7M',
 '6.3M',
 '334k',
 '34M',
 '93M',
 '65M',
 '79M',
 '100M',
 '58M',
 '50M',
 '68M',
 '64M',
 '67M',
 '60M',
 '94M',
 '232k',
 '99M',
 '624k',
 '95M',
 '8.5k',
 '41k',
 '292k',
 '11k',
 '80M',
 '1.7M',
 '74M',
 '62M',
 '69M',
 '75M',
 '98M',
 '85M',
 '82M',
 '96M',
 '87M',
 '71M',
 '86M',
 '91M',
 '81M',
 '92M',
 '83M',
 '88M',
 '704k',
 '862k',
 '899k',
 '378k',
 '266k',
 '375k',
 '1.3M',
 '975k',
 '980k',
 '4.1M',
 '89M',
 '696k',
 '544k',
 '525k',
 '920k',
 '779k',
 '853k',
 '720k',
 '713k',
 '772k',
 '318k',
 '58k',
 '241k',
 '196k',
 '857k',
 '51k',
 '953k',
 '865k',
 '251k',
 '930k',
 '540k',
 '313k',
 '746k',
 '203k',
 '26k',
 '314k',
 '239k',
 '371k',
 '220k',
 '730k',
 '756k',
 '91k',
 '293k',
 '17k',
 '74k',
 '14k',
 '317k',
 '78k',
 '924k',
 '902k',
 '818k',
 '81k',
 '939k',
 '169k',
 '45k',
 '475k',
 '965k',
 '90M',
 '545k',
 '61k',
 '283k',
 '655k',
 '714k',
 '93k',
 '872k',
 '121k',
 '322k',
 '1.0M',
 '976k',
 '172k',
 '238k',
 '549k',
 '206k',
 '954k',
 '444k',
 '717k',
 '210k',
 '609k',
 '308k',
 '705k',
 '306k',
 '904k',
 '473k',
 '175k',
 '350k',
 '383k',
 '454k',
 '421k',
 '70k',
 '812k',
 '442k',
 '842k',
 '417k',
 '412k',
 '459k',
 '478k',
 '335k',
 '782k',
 '721k',
 '430k',
 '429k',
 '192k',
 '200k',
 '460k',
 '728k',
 '496k',
 '816k',
 '414k',
 '506k',
 '887k',
 '613k',
 '243k',
 '569k',
 '778k',
 '683k',
 '592k',
 '319k',
 '186k',
 '840k',
 '647k',
 '191k',
 '373k',
 '437k',
 '598k',
 '716k',
 '585k',
 '982k',
 '222k',
 '219k',
 '55k',
 '948k',
 '323k',
 '691k',
 '511k',
 '951k',
 '963k',
 '25k',
 '554k',
 '351k',
 '27k',
 '82k',
 '208k',
 '913k',
 '514k',
 '551k',
 '29k',
 '103k',
 '898k',
 '743k',
 '116k',
 '153k',
 '209k',
 '353k',
 '499k',
 '173k',
 '597k',
 '809k',
 '122k',
 '411k',
 '400k',
 '801k',
 '787k',
 '237k',
 '50k',
 '643k',
 '986k',
 '97k',
 '516k',
 '837k',
 '780k',
 '961k',
 '269k',
 '20k',
 '498k',
 '600k',
 '749k',
 '642k',
 '881k',
 '72k',
 '656k',
 '601k',
 '221k',
 '228k',
 '108k',
 '940k',
 '176k',
 '33k',
 '663k',
 '34k',
 '942k',
 '259k',
 '164k',
 '458k',
 '245k',
 '629k',
 '28k',
 '288k',
 '775k',
 '785k',
 '636k',
 '916k',
 '994k',
 '309k',
 '485k',
 '914k',
 '903k',
 '608k',
 '500k',
 '54k',
 '562k',
 '847k',
 '957k',
 '688k',
 '811k',
 '270k',
 '48k',
 '329k',
 '523k',
 '921k',
 '874k',
 '981k',
 '784k',
 '280k',
 '24k',
 '518k',
 '754k',
 '892k',
 '154k',
 '860k',
 '364k',
 '387k',
 '626k',
 '161k',
 '879k',
 '39k',
 '970k',
 '170k',
 '141k',
 '160k',
 '144k',
 '143k',
 '190k',
 '376k',
 '193k',
 '246k',
 '73k',
 '658k',
 '992k',
 '253k',
 '420k',
 '404k',
 '470k',
 '226k',
 '240k',
 '89k',
 '234k',
 '257k',
 '861k',
 '467k',
 '157k',
 '44k',
 '676k',
 '67k',
 '552k',
 '885k',
 '1020k',
 '582k',
 '619k']

In [ ]:
# 19000k == 19M

In [33]:
df_copy['Size'].isnull().sum()

np.int64(0)

In [37]:
df_copy['Size']=df_copy['Size'].str.replace('M','000')
df_copy['Size']=df_copy['Size'].str.replace('k','')
df_copy['Size']=df_copy['Size'].replace('Varies with device',np.nan)
df_copy['Size']=df_copy['Size'].astype(float)

In [38]:
df_copy.info()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            9145 non-null   float64
 5   Installs        10840 non-null  str
 6   Type            10839 non-null  str
 7   Price           10840 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(2), int64(1), str(10)
memory usage: 1.2 MB

In [ ]:
df_copy['Installs'].unique()

<StringArray>
[       '10,000+',       '500,000+',     '5,000,000+',    '50,000,000+',
       '100,000+',        '50,000+',     '1,000,000+',    '10,000,000+',
         '5,000+',   '100,000,000+', '1,000,000,000+',         '1,000+',
   '500,000,000+',            '50+',           '100+',           '500+',
            '10+',             '1+',             '5+',             '0+',
              '0',           'Free']
Length: 22, dtype: str

In [ ]:
df_copy['Price'].unique()

<StringArray>
[       '0',    '$4.99',    '$3.99',    '$6.99',    '$1.49',    '$2.99',
    '$7.99',    '$5.99',    '$3.49',    '$1.99',    '$9.99',    '$7.49',
    '$0.99',    '$9.00',    '$5.49',   '$10.00',   '$24.99',   '$11.99',
   '$79.99',   '$16.99',   '$14.99',    '$1.00',   '$29.99',   '$12.99',
    '$2.49',   '$10.99',    '$1.50',   '$19.99',   '$15.99',   '$33.99',
   '$74.99',   '$39.99',    '$3.95',    '$4.49',    '$1.70',    '$8.99',
    '$2.00',    '$3.88',   '$25.99',  '$399.99',   '$17.99',  '$400.00',
    '$3.02',    '$1.76',    '$4.84',    '$4.77',    '$1.61',    '$2.50',
    '$1.59',    '$6.49',    '$1.29',    '$5.00',   '$13.99',  '$299.99',
  '$379.99',   '$37.99',   '$18.99',  '$389.99',   '$19.90',    '$8.49',
    '$1.75',   '$14.00',    '$4.85',   '$46.99',  '$109.99',  '$154.99',
    '$3.08',    '$2.59',    '$4.80',    '$1.96',   '$19.40',    '$3.90',
    '$4.59',   '$15.46',    '$3.04',    '$4.29',    '$2.60',    '$3.28',
    '$4.60',   '$28.99',    '$2.95',    '$2.90',    '$1.97',  '$200.00',
   '$89.99',    '$2.56',   '$30.99',    '$3.61',  '$394.99',    '$1.26',
 'Everyone',    '$1.20',    '$1.04']
Length: 93, dtype: str

In [43]:
chars_to_remove=['+',',','$']
cols_to_clean=['Installs','Price']
for items in chars_to_remove:
    for col in cols_to_clean:
        df_copy[col]=df_copy[col].str.replace(items,'')

In [44]:
df_copy['Price'].unique()

<StringArray>
[     '0',   '4.99',   '3.99',   '6.99',   '1.49',   '2.99',   '7.99',
   '5.99',   '3.49',   '1.99',   '9.99',   '7.49',   '0.99',   '9.00',
   '5.49',  '10.00',  '24.99',  '11.99',  '79.99',  '16.99',  '14.99',
   '1.00',  '29.99',  '12.99',   '2.49',  '10.99',   '1.50',  '19.99',
  '15.99',  '33.99',  '74.99',  '39.99',   '3.95',   '4.49',   '1.70',
   '8.99',   '2.00',   '3.88',  '25.99', '399.99',  '17.99', '400.00',
   '3.02',   '1.76',   '4.84',   '4.77',   '1.61',   '2.50',   '1.59',
   '6.49',   '1.29',   '5.00',  '13.99', '299.99', '379.99',  '37.99',
  '18.99', '389.99',  '19.90',   '8.49',   '1.75',  '14.00',   '4.85',
  '46.99', '109.99', '154.99',   '3.08',   '2.59',   '4.80',   '1.96',
  '19.40',   '3.90',   '4.59',  '15.46',   '3.04',   '4.29',   '2.60',
   '3.28',   '4.60',  '28.99',   '2.95',   '2.90',   '1.97', '200.00',
  '89.99',   '2.56',  '30.99',   '3.61', '394.99',   '1.26',   '1.20',
   '1.04']
Length: 92, dtype: str

In [45]:
df_copy['Installs'].unique()

<StringArray>
[     '10000',     '500000',    '5000000',   '50000000',     '100000',
      '50000',    '1000000',   '10000000',       '5000',  '100000000',
 '1000000000',       '1000',  '500000000',         '50',        '100',
        '500',         '10',          '1',          '5',          '0']
Length: 20, dtype: str

In [ ]:
df_copy['Installs']=df_copy['Installs'].astype(int)

0           10000
1          500000
2         5000000
3        50000000
4          100000
           ...
10836        5000
10837         100
10838        1000
10839        1000
10840    10000000
Name: Installs, Length: 10840, dtype: int64

In [55]:
df_copy['Price'] = df_copy['Price'].astype('float')

In [56]:
print(df_copy['Price'].unique())

[  0.     4.99   3.99   6.99   1.49   2.99   7.99   5.99   3.49   1.99
   9.99   7.49   0.99   9.     5.49  10.    24.99  11.99  79.99  16.99
  14.99   1.    29.99  12.99   2.49  10.99   1.5   19.99  15.99  33.99
  74.99  39.99   3.95   4.49   1.7    8.99   2.     3.88  25.99 399.99
  17.99 400.     3.02   1.76   4.84   4.77   1.61   2.5    1.59   6.49
   1.29   5.    13.99 299.99 379.99  37.99  18.99 389.99  19.9    8.49
   1.75  14.     4.85  46.99 109.99 154.99   3.08   2.59   4.8    1.96
  19.4    3.9    4.59  15.46   3.04   4.29   2.6    3.28   4.6   28.99
   2.95   2.9    1.97 200.    89.99   2.56  30.99   3.61 394.99   1.26
   1.2    1.04]

In [57]:
df_copy.info()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            9145 non-null   float64
 5   Installs        10840 non-null  int64
 6   Type            10839 non-null  str
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(3), int64(2), str(8)
memory usage: 1.2 MB

In [58]:
# Handling last updated feature
df_copy['Last Updated'].unique()

<StringArray>
[   'January 7, 2018',   'January 15, 2018',     'August 1, 2018',
       'June 8, 2018',      'June 20, 2018',     'March 26, 2017',
     'April 26, 2018',      'June 14, 2018', 'September 20, 2017',
       'July 3, 2018',
 ...
  'November 23, 2015',      'June 17, 2012',  'February 27, 2015',
  'December 18, 2013',   'February 6, 2012',  'November 25, 2014',
       'May 19, 2016',   'January 20, 2014',  'February 16, 2014',
     'March 23, 2014']
Length: 1377, dtype: str

In [60]:
df_copy['Last Updated']=pd.to_datetime(df_copy['Last Updated'])

In [65]:
df_copy['Day']=df_copy['Last Updated'].dt.day
df_copy['Month']=df_copy['Last Updated'].dt.month
df_copy['Year']=df_copy['Last Updated'].dt.year

In [67]:
df_copy.info()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            9145 non-null   float64
 5   Installs        10840 non-null  int64
 6   Type            10839 non-null  str
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  datetime64[us]
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
 13  Day             10840 non-null  int32
 14  Month           10840 non-null  int32
 15  Year            10840 non-null  int32
dtypes: datetime64[us](1), float64(3), int32(3), int64(2), str(7)
memory usage: 1.3 MB

In [69]:
df_copy.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Day,Month,Year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018

In [74]:
df_copy.to_csv('Data/google_cleaned_data')

OSError: Cannot save file into a non-existent directory: 'Data'