In [1]:
print("h")

h

# Data Manipulation and Analysis with Pandas

Data manipulation and analysis are key task in any data science or data analysis project.Pandas provide awide range of function for data manipulation and analysis,making it easier to clean, transorm and extract insight from data.

In [2]:
import pandas as pd

In [16]:
df = pd.read_csv('nwe.csv')
df.head(6)

         Date     Category    Value      Product  Sales   Region
0  2025-03-19     Clothing  2034.64      T-Shirt   19.0  Central
1  2025-07-07  Electronics  2955.66      Monitor   55.0    North
2  2025-08-11  Electronics  2149.04   Smartphone   24.0      NaN
3  2025-01-31    Groceries  4151.58         Rice   58.0  Central
4  2025-10-23  Electronics  2969.15       Laptop   57.0    North
5  2025-03-10          NaN  1519.09  Cricket Bat  139.0    North

In [17]:
df.tail(5)

          Date     Category    Value     Product  Sales   Region
95  2025-12-02       Sports  1084.80    Yoga Mat  199.0    North
96  2025-05-16  Electronics  4103.52  Smartphone    NaN  Central
97  2025-07-21  Electronics   210.22  Headphones  162.0    South
98  2025-10-27  Electronics  4792.42  Smartphone  169.0  Central
99  2025-06-16    Groceries  3631.32        Eggs   39.0     East

In [18]:
df.describe()

             Value       Sales
count    96.000000   97.000000
mean   2499.508229  102.556701
std    1448.286168   57.689537
min     101.140000    1.000000
25%    1188.670000   56.000000
50%    2522.585000  108.000000
75%    3793.367500  156.000000
max    4966.170000  199.000000

In [19]:
df.dtypes

Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object

In [20]:
# Handling Missing value
df.isnull()

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False    True
3   False     False  False    False  False   False
4   False     False  False    False  False   False
..    ...       ...    ...      ...    ...     ...
95  False     False  False    False  False   False
96  False     False  False    False   True   False
97  False     False  False    False  False   False
98  False     False  False    False  False   False
99  False     False  False    False  False   False

[100 rows x 6 columns]

In [21]:
df.isnull().any(axis=1)

0     False
1     False
2      True
3     False
4     False
      ...
95    False
96     True
97    False
98    False
99    False
Length: 100, dtype: bool

In [22]:
df.isnull().any()

Date        True
Category    True
Value       True
Product     True
Sales       True
Region      True
dtype: bool

In [23]:
df.isnull().sum()

Date        3
Category    3
Value       4
Product     3
Sales       3
Region      2
dtype: int64

In [26]:
dfFilled = df.fillna(0)
dfFilled

          Date     Category    Value     Product  Sales   Region
0   2025-03-19     Clothing  2034.64     T-Shirt   19.0  Central
1   2025-07-07  Electronics  2955.66     Monitor   55.0    North
2   2025-08-11  Electronics  2149.04  Smartphone   24.0        0
3   2025-01-31    Groceries  4151.58        Rice   58.0  Central
4   2025-10-23  Electronics  2969.15      Laptop   57.0    North
..         ...          ...      ...         ...    ...      ...
95  2025-12-02       Sports  1084.80    Yoga Mat  199.0    North
96  2025-05-16  Electronics  4103.52  Smartphone    0.0  Central
97  2025-07-21  Electronics   210.22  Headphones  162.0    South
98  2025-10-27  Electronics  4792.42  Smartphone  169.0  Central
99  2025-06-16    Groceries  3631.32        Eggs   39.0     East

[100 rows x 6 columns]

In [29]:
# filling missing value with the mean of the column
df['Sales_fillNA'] = df['Sales'].fillna(df['Sales'].mean())
df

          Date     Category    Value     Product  Sales   Region  Sales_fillNA
0   2025-03-19     Clothing  2034.64     T-Shirt   19.0  Central     19.000000
1   2025-07-07  Electronics  2955.66     Monitor   55.0    North     55.000000
2   2025-08-11  Electronics  2149.04  Smartphone   24.0      NaN     24.000000
3   2025-01-31    Groceries  4151.58        Rice   58.0  Central     58.000000
4   2025-10-23  Electronics  2969.15      Laptop   57.0    North     57.000000
..         ...          ...      ...         ...    ...      ...           ...
95  2025-12-02       Sports  1084.80    Yoga Mat  199.0    North    199.000000
96  2025-05-16  Electronics  4103.52  Smartphone    NaN  Central    102.556701
97  2025-07-21  Electronics   210.22  Headphones  162.0    South    162.000000
98  2025-10-27  Electronics  4792.42  Smartphone  169.0  Central    169.000000
99  2025-06-16    Groceries  3631.32        Eggs   39.0     East     39.000000

[100 rows x 7 columns]

In [34]:
df.dtypes

Date                str
Category            str
Value           float64
Product             str
Sales           float64
Region              str
Sales_fillNA    float64
dtype: object

In [36]:
#Renaming Column 
df = df.rename(columns={'Date':'Sales Date'})
df.head(5)

   Sales Date     Category    Value     Product  Sales   Region  Sales_fillNA
0  2025-03-19     Clothing  2034.64     T-Shirt   19.0  Central          19.0
1  2025-07-07  Electronics  2955.66     Monitor   55.0    North          55.0
2  2025-08-11  Electronics  2149.04  Smartphone   24.0      NaN          24.0
3  2025-01-31    Groceries  4151.58        Rice   58.0  Central          58.0
4  2025-10-23  Electronics  2969.15      Laptop   57.0    North          57.0

In [45]:
# change Datatypes
df['Value_new'] = df['Value'].fillna(df['Value'].mean())
df.tail(20)

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new
80,2025-08-02,Sports,NaN,Tennis Racket,160.0,South,160.000000,2499.508229
81,2025-09-27,Electronics,3576.73,Laptop,42.0,East,42.000000,3576.730000
82,NaN,Electronics,1088.66,Headphones,161.0,East,161.000000,1088.660000
83,2025-04-16,Sports,1520.81,Yoga Mat,173.0,South,173.000000,1520.810000
84,2025-06-27,Clothing,4038.03,Jacket,10.0,North,10.000000,4038.030000
85,2025-09-16,Electronics,2800.14,Smartphone,132.0,West,132.000000,2800.140000
86,2025-08-17,Furniture,620.78,Cabinet,169.0,West,169.000000,620.780000
87,2025-07-21,Sports,4854.53,Tennis Racket,177.0,South,177.000000,4854.530000
88,2025-06-25,Furniture,1073.26,Desk,104.0,East,104.000000,1073.260000
89,2025-03-08,Electronics,169.85,NaN,111.0,South,111.000000,169.850000
90,2025-02-13,Electronics,3359.62,Tablet,130.0,East,130.000000,3359.620000
91,2025-05-05,NaN,3494.16,Football,118.0,South,118.000000,3494.160000
92,NaN,Furniture,2284.54,Sofa,94.0,East,94.000000,2284.540000
93,2025-06-15,Sports,NaN,Tennis Racket,56.0,East,56.000000,2499.508229
94,2025-01-01,Furniture,1743.13,Chair,122.0,East,122.000000,1743.130000
95,2025-12-02,Sports,1084.80,Yoga Mat,199.0,North,199.000000,1084.800000
96,2025-05-16,Electronics,4103.52,Smartphone,NaN,Central,102.556701,4103.520000
97,2025-07-21,Electronics,210.22,Headphones,162.0,South,162.000000,210.220000
98,2025-10-27,Electronics,4792.42,Smartphone,169.0,Central,169.000000,4792.420000
99,2025-06-16,Groceries,3631.32,Eggs,39.0,East,39.000000,3631.320000

In [46]:
df['Value_new'] = df['Value'].fillna(df['Value'].mean()).astype(int)
df.tail(20)

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new
80,2025-08-02,Sports,NaN,Tennis Racket,160.0,South,160.000000,2499
81,2025-09-27,Electronics,3576.73,Laptop,42.0,East,42.000000,3576
82,NaN,Electronics,1088.66,Headphones,161.0,East,161.000000,1088
83,2025-04-16,Sports,1520.81,Yoga Mat,173.0,South,173.000000,1520
84,2025-06-27,Clothing,4038.03,Jacket,10.0,North,10.000000,4038
85,2025-09-16,Electronics,2800.14,Smartphone,132.0,West,132.000000,2800
86,2025-08-17,Furniture,620.78,Cabinet,169.0,West,169.000000,620
87,2025-07-21,Sports,4854.53,Tennis Racket,177.0,South,177.000000,4854
88,2025-06-25,Furniture,1073.26,Desk,104.0,East,104.000000,1073
89,2025-03-08,Electronics,169.85,NaN,111.0,South,111.000000,169
90,2025-02-13,Electronics,3359.62,Tablet,130.0,East,130.000000,3359
91,2025-05-05,NaN,3494.16,Football,118.0,South,118.000000,3494
92,NaN,Furniture,2284.54,Sofa,94.0,East,94.000000,2284
93,2025-06-15,Sports,NaN,Tennis Racket,56.0,East,56.000000,2499
94,2025-01-01,Furniture,1743.13,Chair,122.0,East,122.000000,1743
95,2025-12-02,Sports,1084.80,Yoga Mat,199.0,North,199.000000,1084
96,2025-05-16,Electronics,4103.52,Smartphone,NaN,Central,102.556701,4103
97,2025-07-21,Electronics,210.22,Headphones,162.0,South,162.000000,210
98,2025-10-27,Electronics,4792.42,Smartphone,169.0,Central,169.000000,4792
99,2025-06-16,Groceries,3631.32,Eggs,39.0,East,39.000000,3631

In [52]:
df['New_sales'] = df['Sales'].apply(lambda x:x**2)
df.head(4)

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new,New_value,New_sales
0,2025-03-19,Clothing,2034.64,T-Shirt,19.0,Central,19.0,2034,4.139760e+06,361.0
1,2025-07-07,Electronics,2955.66,Monitor,55.0,North,55.0,2955,8.735926e+06,3025.0
2,2025-08-11,Electronics,2149.04,Smartphone,24.0,NaN,24.0,2149,4.618373e+06,576.0
3,2025-01-31,Groceries,4151.58,Rice,58.0,Central,58.0,4151,1.723562e+07,3364.0

In [53]:
## Data aggregation and grouping

grouped_mean = df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Basketball       3133.150000
Bread            4113.000000
Cabinet          1171.733333
Chair            1029.633333
Comics           1128.947500
Cricket Bat      2061.358333
Desk             2164.075714
Eggs             2805.118571
Football         2455.733333
Headphones       2038.822500
Jacket           3418.262000
Jeans             570.610000
Laptop           2250.925000
Magazine         2947.366667
Milk             3878.003333
Monitor          1575.565000
Notebook         3048.380000
Novel            4023.115000
Rice             2336.205000
Smartphone       2933.228571
Sofa             1810.300000
Sweater          3483.420000
T-Shirt          3468.750000
Table            2288.695000
Tablet           3843.610000
Tea              3846.526667
Tennis Racket    3022.690000
Yoga Mat         1302.805000
Name: Value, dtype: float64

In [58]:
Grouped_sum=df.groupby(['Product','Region'])['Value'].sum()
print(Grouped_sum)

Product        Region
Basketball     Central    3133.15
Bread          South      4113.00
Cabinet        North       844.72
               South      2049.70
               West        620.78
                           ...
Tennis Racket  East       2895.92
               North      1317.62
               South      4854.53
Yoga Mat       North      1084.80
               South      1520.81
Name: Value, Length: 66, dtype: float64

In [59]:
# Aggregate Multiple Functions
Grouped_aggregate = df.groupby('Region')['Value'].agg(['mean','sum','count'])
Grouped_aggregate

                mean       sum  count
Region
Central  3259.041250  52144.66     16
East     2781.382400  69534.56     25
North    2208.163158  41955.10     19
South    1912.917647  32519.60     17
West     2333.325882  39666.54     17

In [60]:
# Merging and joining Dataframes
# create sample Dataframes

df1 = pd.DataFrame({'key':['A','B','C'],'Value1':[1,2,3]})
df2 = pd.DataFrame({'key':['A','B','D'],'Value2':[4,5,6]})

In [61]:
df1

  key  Value1
0   A       1
1   B       2
2   C       3

In [62]:
df2

  key  Value2
0   A       4
1   B       5
2   D       6

In [63]:
#Merge DataFrame on the 'Key Column'
pd.merge(df1,df2,on="key",how="inner")

  key  Value1  Value2
0   A       1       4
1   B       2       5

In [64]:
pd.merge(df1,df2,on="key",how="outer")

  key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [65]:
pd.merge(df1,df2,on="key",how="left")

  key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [66]:
pd.merge(df1,df2,on="key",how="right")

  key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6