In [1]:
print("g")

g

#### Pandas Dataframe and series

##### pandas is the powerful data manipulation library in python, widely used for data analysis and data cleaning. It provides two primary data structure: Series and Datframes.A Series is the one dimensional array like object,while a dataframe is a two-dimenstional,size-mutual,and potentially hetrogeneous tabular data structure with labeled axes(rows and colums).

In [5]:
## Series 
# A pandas series is a one dimensional array-like object that can hold any data type. 

import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [7]:
# create a series from to dictonary
data = {'a': 1, 'b': 2 ,'c': 3,'d':4}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
d    4
dtype: int64

In [8]:
data = [10,20,30,40]
index = ['a','b','c','d']
pd.Series(data,index = index)

a    10
b    20
c    30
d    40
dtype: int64

In [11]:
# DataFrame
# Create a datagram from a Dictonary of list 

data = {
    'Name' : ['krish','john','jack'],
    'Age' : [23,12,64],
    'City': ['Banglore','New York','Florida']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  krish   23  Banglore
1   john   12  New York
2   jack   64   Florida
<class 'pandas.DataFrame'>

In [38]:
# Create a list of data frames from a list of Dictonaries
data = [
     {'Name':'Krish','Age':32,'City':'Bangalore'},
     {'Name':'Sachin','Age':21,'City':'Mumbai'},
     {'Name':'Ramesh','Age':30,'City':'jaipur'}
]
dff = pd.DataFrame(data)
print(dff)
print(type(dff))

     Name  Age       City
0   Krish   32  Bangalore
1  Sachin   21     Mumbai
2  Ramesh   30     jaipur
<class 'pandas.DataFrame'>

In [18]:
df = pd.read_csv('sales_data.csv')
df.head(5)

,Index No,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,1,TXN100001,2025-03-13,Electronics,Laptop,9,374.89,3374.01,North,Net Banking
1,2,TXN100002,2025-02-17,Electronics,Smartwatch,14,57.36,803.04,South,Credit Card
2,3,TXN100003,2025-11-29,Sports,Tennis Racket,1,846.26,846.26,West,Credit Card
3,4,TXN100004,2025-01-04,Home Appliances,Fan,9,1216.05,10944.45,South,UPI
4,5,TXN100005,2025-06-22,Clothing,Jacket,5,330.82,1654.10,North,Cash

In [19]:
df.tail(5)

,Index No,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
295,296,TXN100296,2025-10-24,Sports,Dumbbells,9,1450.94,13058.46,South,Cash
296,297,TXN100297,2025-11-14,Sports,Dumbbells,6,791.11,4746.66,West,Credit Card
297,298,TXN100298,2025-02-26,Furniture,Office Chair,19,1422.83,27033.77,South,Cash
298,299,TXN100299,2025-12-20,Home Appliances,Vacuum Cleaner,14,235.63,3298.82,South,UPI
299,300,TXN100300,2025-02-01,Sports,Tennis Racket,16,1310.50,20968.00,South,Net Banking

In [20]:
#Accessing Data from Dataframe
df

,Index No,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,1,TXN100001,2025-03-13,Electronics,Laptop,9,374.89,3374.01,North,Net Banking
1,2,TXN100002,2025-02-17,Electronics,Smartwatch,14,57.36,803.04,South,Credit Card
2,3,TXN100003,2025-11-29,Sports,Tennis Racket,1,846.26,846.26,West,Credit Card
3,4,TXN100004,2025-01-04,Home Appliances,Fan,9,1216.05,10944.45,South,UPI
4,5,TXN100005,2025-06-22,Clothing,Jacket,5,330.82,1654.10,North,Cash
...,...,...,...,...,...,...,...,...,...,...
295,296,TXN100296,2025-10-24,Sports,Dumbbells,9,1450.94,13058.46,South,Cash
296,297,TXN100297,2025-11-14,Sports,Dumbbells,6,791.11,4746.66,West,Credit Card
297,298,TXN100298,2025-02-26,Furniture,Office Chair,19,1422.83,27033.77,South,Cash
298,299,TXN100299,2025-12-20,Home Appliances,Vacuum Cleaner,14,235.63,3298.82,South,UPI
299,300,TXN100300,2025-02-01,Sports,Tennis Racket,16,1310.50,20968.00,South,Net Banking

In [28]:
df['Product Category']
type(df['Product Category'])

pandas.Series

In [29]:
df.loc[0]

Index No                      1
Transaction ID        TXN100001
Date                 2025-03-13
Product Category    Electronics
Product Name             Laptop
Units Sold                    9
Unit Price               374.89
Total Revenue           3374.01
Region                    North
Payment Method      Net Banking
Name: 0, dtype: object

In [37]:
print(df.iloc[0])

Index No                      1
Transaction ID        TXN100001
Date                 2025-03-13
Product Category    Electronics
Product Name             Laptop
Units Sold                    9
Unit Price               374.89
Total Revenue           3374.01
Region                    North
Payment Method      Net Banking
Name: 0, dtype: object

In [ ]:
dff

     Name  Age       City
0   Krish   32  Bangalore
1  Sachin   21     Mumbai
2  Ramesh   30     jaipur

In [42]:
dff['Name']

0     Krish
1    Sachin
2    Ramesh
Name: Name, dtype: str

In [49]:
# Acessing a specific element
print(dff.at[2,'City'])
print(dff.at[1,'Age'])

jaipur
21

In [51]:
# Accessing a specific  element using iat

dff.iat[2,2]

'jaipur'

In [94]:
# Data Manuplation with data frames

# Adding a column
dff['salary'] = [3000,2000,6000]
dff

     Name  Age       City  salary
0   Krish   32  Bangalore    3000
1  Sachin   21     Mumbai    2000
2  Ramesh   30     jaipur    6000

In [96]:
# remove The column
dff.drop('salary',axis=1)

     Name  Age       City
0   Krish   32  Bangalore
1  Sachin   21     Mumbai
2  Ramesh   30     jaipur

In [97]:
dff

     Name  Age       City  salary
0   Krish   32  Bangalore    3000
1  Sachin   21     Mumbai    2000
2  Ramesh   30     jaipur    6000

In [98]:
# For deleting the column permantely we use (inplace = True)

dff.drop('salary',axis=1,inplace=True)

In [99]:
dff

     Name  Age       City
0   Krish   32  Bangalore
1  Sachin   21     Mumbai
2  Ramesh   30     jaipur

In [101]:
# Add age to the column 
dff['Age']=dff['Age']+1

In [102]:
dff

     Name  Age       City
0   Krish   33  Bangalore
1  Sachin   22     Mumbai
2  Ramesh   31     jaipur

In [103]:
dff.drop(0)

     Name  Age    City
1  Sachin   22  Mumbai
2  Ramesh   31  jaipur

In [104]:
dff

     Name  Age       City
0   Krish   33  Bangalore
1  Sachin   22     Mumbai
2  Ramesh   31     jaipur

In [105]:
dff.drop(0,inplace=True)

In [106]:
dff

     Name  Age    City
1  Sachin   22  Mumbai
2  Ramesh   31  jaipur

In [115]:
# Display the data type of the each column 
print("Data Type:\n",df.dtypes)

Data Type:
 Index No              int64
Transaction ID          str
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object

In [116]:
#Describes the dataFrames
print("Statistical Summary:\n",df.describe)

Statistical Summary:
 <bound method NDFrame.describe of      Index No Transaction ID        Date Product Category    Product Name  \
0           1      TXN100001  2025-03-13      Electronics          Laptop
1           2      TXN100002  2025-02-17      Electronics      Smartwatch
2           3      TXN100003  2025-11-29           Sports   Tennis Racket
3           4      TXN100004  2025-01-04  Home Appliances             Fan
4           5      TXN100005  2025-06-22         Clothing          Jacket
..        ...            ...         ...              ...             ...
295       296      TXN100296  2025-10-24           Sports       Dumbbells
296       297      TXN100297  2025-11-14           Sports       Dumbbells
297       298      TXN100298  2025-02-26        Furniture    Office Chair
298       299      TXN100299  2025-12-20  Home Appliances  Vacuum Cleaner
299       300      TXN100300  2025-02-01           Sports   Tennis Racket

     Units Sold  Unit Price  Total Revenue Region Payment Method
0             9      374.89        3374.01  North    Net Banking
1            14       57.36         803.04  South    Credit Card
2             1      846.26         846.26   West    Credit Card
3             9     1216.05       10944.45  South            UPI
4             5      330.82        1654.10  North           Cash
..          ...         ...            ...    ...            ...
295           9     1450.94       13058.46  South           Cash
296           6      791.11        4746.66   West    Credit Card
297          19     1422.83       27033.77  South           Cash
298          14      235.63        3298.82  South            UPI
299          16     1310.50       20968.00  South    Net Banking

[300 rows x 10 columns]>

In [117]:
df.describe()

         Index No  Units Sold   Unit Price  Total Revenue
count  300.000000  300.000000   300.000000     300.000000
mean   150.500000   10.403333   781.304233    7996.902933
std     86.746758    5.906234   438.311908    6892.245422
min      1.000000    1.000000    24.410000      78.530000
25%     75.750000    5.000000   405.615000    2620.170000
50%    150.500000   10.000000   798.490000    5598.115000
75%    225.250000   15.250000  1133.605000   11666.677500
max    300.000000   20.000000  1499.970000   29530.200000