### Label Encoding

Label encoding and Ordinal Encoding are two techinque used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable. the label are usually assign in the alphabetical order or based on the frequency of the categories.For Example: If we have a categorical variable "color" with threee possible values(red,green,blue)we can represent it using label encoding  as follows:

1. Red:1
2. Green:2
3. Blue:3

In [ ]:
import pandas as pd

In [4]:
from sklearn.preprocessing import OneHotEncoder

In [5]:
df = pd.DataFrame({'Color': ['Red', 'Blue', 'Green', 'Green', 'Red', 'Blue']})

In [7]:
df.head()

   Color
0    Red
1   Blue
2  Green
3  Green
4    Red

In [12]:
from sklearn.preprocessing import LabelEncoder
lbl = LabelEncoder()

In [16]:
lbl.fit_transform(df[['Color']])

c:\Users\itssa\anaconda3\envs\dsenv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [18]:
lbl.transform([['Red']])

c:\Users\itssa\anaconda3\envs\dsenv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [19]:
lbl.transform([['Green']])

c:\Users\itssa\anaconda3\envs\dsenv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

In [20]:
lbl.transform([["Blue"]])

c:\Users\itssa\anaconda3\envs\dsenv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

### Ordinal Encoding 

It is used to encode categorical data that have an intrinsic order or ranking. in this technique each category is assigned a numerical value based on its position in the order. For Example:- if we have a categorical variable "eduction level" with four possible value (high school,collage,graduate,post-graduate),we can represent it using ordinal encoding as follows:

1. High School:1
2. College:2
3. Graduate:3
4. post-Graduate:4

In [ ]:
# ordinal Encoding

from sklearn.preprocessing import OrdinalEncoder

In [24]:
# Create a sample dataframe with an ordinal variable
df = pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [25]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [26]:
# create an istance of Ordinal Encoder and perform fit_transform

In [ ]:
encoder = OrdinalEncoder(categories =[['small','medium','large']])

In [28]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [30]:
encoder.transform([['small']])

c:\Users\itssa\anaconda3\envs\dsenv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

### Target Guided Ordinal Encoding :-

It is the technique used to encode categorical based on the relationship with the target variable.this encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine.

In target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean and median of the target variable for the category.This create a monotonic relationship between the categorical variable and the target variable,which can improve the pridictive power of our model.

In [32]:
import pandas as pd
#create a sample dataframe with a categorical variable and a target variable
df=pd.DataFrame({
    'city':['New York','Londan','Paris','Tokyo','New York', 'Paris'],
    'Price':[200,150,300,250,180,320]
})

In [33]:
df

       city  Price
0  New York    200
1    Londan    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [38]:
mean_price=df.groupby('city')['Price'].mean().to_dict()

In [ ]:
mean_price

{'Londan': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [41]:
df['city_encoded']=df['city'].map(mean_price)

In [42]:
df

       city  Price  city_encoded
0  New York    200         190.0
1    Londan    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [ ]:
df[['city','city_encoded']]

       city  city_encoded
0  New York         190.0
1    Londan         150.0
2     Paris         310.0
3     Tokyo         250.0
4  New York         190.0
5     Paris         310.0

In [47]:
# assignment 

import seaborn as sns
tips = sns.load_dataset('tips')
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [49]:
time_mean = tips.groupby('time')['total_bill'].mean()

In [50]:
time_mean

time
Lunch     17.168676
Dinner    20.797159
Name: total_bill, dtype: float64

In [52]:
mapping = time_mean.to_dict()
print(mapping)

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [ ]:
tips['time_target_encoded'] = tips['time'].map(mapping)

In [63]:
tips[['time','total_bill','time_target_encoded']].head()

     time  total_bill time_target_encoded
0  Dinner       16.99           20.797159
1  Dinner       10.34           20.797159
2  Dinner       21.01           20.797159
3  Dinner       23.68           20.797159
4  Dinner       24.59           20.797159